### ISSUE TITLE
Bug when create from classes

### ISSUE THREAD

**Issue by harlyman** [jeddict/jeddict#138]
Message : org.netbeans.jpa.modeler.spec.extend.Attribute.loadAttribute(Attribute.java:168)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jpa.modeler.spec.extend.Attribute.loadAttribute(Attribute.java:168)
	at org.netbeans.jpa.modeler.spec.extend.PersistenceBaseAttribute.loadAttribute(PersistenceBaseAttribute.java:48)
	at org.netbeans.jpa.modeler.spec.Basic.load(Basic.java:83)
	at org.netbeans.jpa.modeler.spec.Attributes.load(Attributes.java:195)
	at org.netbeans.jpa.modeler.spec.ManagedClass.load(ManagedClass.java:42)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.load(IdentifiableClass.java:92)
	at org.netbeans.jpa.modeler.spec.Entity.load(Entity.java:186)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:51)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:41)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:83)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:609)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:380)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:363)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:204)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:201)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:201)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:334)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:415)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:407)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator.generateJPAModel(JPAModelGenerator.java:41)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor.generateJPAModel(RevEngWizardDescriptor.java:203)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor$1.run(RevEngWizardDescriptor.java:126)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by jGauravGupta** [comment]
Hi @harlyman ,
Please attach the sample modeler file.

**Comment by harlyman** [comment]
2017-02-14 13:45 GMT-03:00 Gaurav Gupta <notifications@github.com>:

**Comment by jGauravGupta** [comment]
@harlyman please attach the file from github.

**Comment by jGauravGupta** [comment]
Hi @harlyman ,
Please attach the sample java source.
