### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by debradsh** [jeddict/jeddict#184]
Message : org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.createNewModelerFile(JPAModelerUtil.java:817)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.createNewModelerFile(JPAModelerUtil.java:817)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.createNewModelerFile(JPAModelerUtil.java:804)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator.runImpl(JavaPersistenceModelGenerator.java:280)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator.run(JavaPersistenceModelGenerator.java:208)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator.generateModal(JavaPersistenceModelGenerator.java:104)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator.generateModel(JavaPersistenceModelGenerator.java:87)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor.createModel(DBImportWizardDescriptor.java:181)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor.access$100(DBImportWizardDescriptor.java:55)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor$1.run(DBImportWizardDescriptor.java:93)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by javydreamercsw** [comment]
More details are appreciated, but give version 4 a try. It solved errors I had creating the model. Might be related.
