### ISSUE TITLE
DataBase Import error

### ISSUE THREAD

**Issue by debradsh** [jeddict/jeddict#185]
Message : Passed null to FileOwnerQuery.getOwner(FileObject)

StackTrace : 
java.lang.NullPointerException: Passed null to FileOwnerQuery.getOwner(FileObject)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:109)
	at net.rwx.netbeans.netesta.files.CompiledFileObserver.<init>(CompiledFileObserver.java:58)
	at net.rwx.netbeans.netesta.NetestaHandler.<init>(NetestaHandler.java:41)
	at net.rwx.netbeans.netesta.DataObjectOpenAndCloseListener.addChangeListenerIfTestableSourceCode(DataObjectOpenAndCloseListener.java:75)
	at net.rwx.netbeans.netesta.DataObjectOpenAndCloseListener.addChangeListenerIfTestableSourceCode(DataObjectOpenAndCloseListener.java:69)
	at net.rwx.netbeans.netesta.DataObjectOpenAndCloseListener.propertyChange(DataObjectOpenAndCloseListener.java:52)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.netbeans.core.windows.RegistryImpl.doFirePropertyChange(RegistryImpl.java:329)
	at org.netbeans.core.windows.RegistryImpl.topComponentOpened(RegistryImpl.java:188)
	at org.netbeans.core.windows.WindowManagerImpl.notifyRegistryTopComponentOpened(WindowManagerImpl.java:1183)
	at org.netbeans.core.windows.WindowManagerImpl.notifyTopComponentOpened(WindowManagerImpl.java:1151)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:798)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:354)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1261)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1226)
	at org.openide.windows.TopComponent.open(TopComponent.java:497)
	at org.openide.windows.TopComponent.open(TopComponent.java:477)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:141)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:72)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:64)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.modules.j2ee.persistence.wizard.fromdb.ProgressPanel.open(ProgressPanel.java:83)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor$2.run(DBImportWizardDescriptor.java:121)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" v="2.7" status="GENERATED" sm="false" xs="false" id="_149079942142361" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity xre="false" abs="false" class="Role" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142362">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="name" id="_149079942142371">
                <jpa:bv/>
                <jpa:column name="Name" unique="false" nullable="false" insertable="true" updatable="true" table="Role" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="description" id="_149079942142372">
                <jpa:bv/>
                <jpa:column name="Description" unique="false" nullable="false" insertable="true" updatable="true" table="Role" length="500"/>
            </jpa:basic>
            <jpa:many-to-one connected-entity-id="_149079942142369" connected-attribute-id="_1490799421424120" v="true" name="appId" id="_149079942142374">
                <jpa:bv/>
                <jpa:join-column name="APPID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142368" connected-attribute-id="_1490799421424113" v="true" name="userRoleCollection" id="_149079942142375">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:many-to-many own="true" connected-entity-id="_149079942142365" connected-attribute-id="_1490799421423100" v="true" name="permissionCollection" id="_149079942142373">
                <jpa:bv/>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149079942142370">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="Role"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Role"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Organization" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142363">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="name" id="_149079942142377">
                <jpa:bv/>
                <jpa:column name="Name" unique="false" nullable="false" insertable="true" updatable="true" table="Organization" length="50"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="meta" id="_149079942142378">
                <jpa:bv/>
                <jpa:column name="META" unique="false" nullable="true" insertable="true" updatable="true" table="Organization" length="2147483647"/>
            </jpa:basic>
            <jpa:many-to-one connected-entity-id="_149079942142363" connected-attribute-id="_149079942142379" v="true" name="parentID" id="_149079942142380">
                <jpa:bv/>
                <jpa:join-column name="PARENT_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one optional="false" connected-entity-id="_149079942142367" connected-attribute-id="_1490799421423110" v="true" name="typeID" id="_149079942142381">
                <jpa:bv/>
                <jpa:join-column name="TYPEID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142363" connected-attribute-id="_149079942142380" v="true" name="organizationCollection" id="_149079942142379">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142366" connected-attribute-id="_1490799421423105" v="true" name="lineOfBusinessCollection" id="_149079942142382">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149079942142376">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="Organization"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Organization"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="UserProfile" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142364">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="login" id="_149079942142384">
                <jpa:bv/>
                <jpa:column name="Login" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="firstName" id="_149079942142385">
                <jpa:bv/>
                <jpa:column name="FirstName" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="lastName" id="_149079942142386">
                <jpa:bv/>
                <jpa:column name="LastName" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="email" id="_149079942142387">
                <jpa:bv/>
                <jpa:column name="Email" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile" length="300"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="password" id="_149079942142388">
                <jpa:bv/>
                <jpa:column name="Password" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.util.Date" v="true" name="lastLoginDate" id="_149079942142389">
                <jpa:bv/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
                <jpa:column name="LastLoginDate" unique="false" nullable="true" insertable="true" updatable="true" table="UserProfile"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="java.util.Date" v="true" name="dateCreated" id="_149079942142390">
                <jpa:bv/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
                <jpa:column name="DateCreated" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Character" v="true" name="changePassword" id="_149079942142391">
                <jpa:bv/>
                <jpa:column name="ChangePassword" unique="false" nullable="true" insertable="true" updatable="true" table="UserProfile"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.util.Date" v="true" name="passwordChangeDate" id="_149079942142392">
                <jpa:bv/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
                <jpa:column name="PasswordChangeDate" unique="false" nullable="true" insertable="true" updatable="true" table="UserProfile"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="loginType" id="_149079942142393">
                <jpa:bv/>
                <jpa:column name="LoginType" unique="false" nullable="true" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="idKey" id="_149079942142394">
                <jpa:bv/>
                <jpa:column name="IdKey" unique="false" nullable="true" insertable="true" updatable="true" table="UserProfile" length="50"/>
            </jpa:basic>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142368" connected-attribute-id="_1490799421424114" v="true" name="userRoleCollection" id="_149079942142396">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:many-to-many own="true" connected-entity-id="_149079942142366" connected-attribute-id="_1490799421423104" v="true" name="lineOfBusinessCollection" id="_149079942142395">
                <jpa:bv/>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149079942142383">
                <jpa:bv/>
                <jpa:column name="id" unique="false" nullable="false" insertable="true" updatable="true" table="UserProfile"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="UserProfile"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Permission" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142365">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="prgmKey" id="_149079942142398">
                <jpa:bv/>
                <jpa:column name="PrgmKey" unique="false" nullable="false" insertable="true" updatable="true" table="Permission" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="description" id="_149079942142399">
                <jpa:bv/>
                <jpa:column name="Description" unique="false" nullable="false" insertable="true" updatable="true" table="Permission" length="500"/>
            </jpa:basic>
            <jpa:many-to-many connected-entity-id="_149079942142362" connected-attribute-id="_149079942142373" v="true" name="roleCollection" id="_1490799421423100">
                <jpa:bv/>
                <jpa:join-table name="ROLE_PERMISSION">
                    <jpa:join-column name="PER_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                    <jpa:inverse-join-column name="ROLE_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                </jpa:join-table>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149079942142397">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="Permission"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Permission"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="LineOfBusiness" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142366">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="name" id="_1490799421423102">
                <jpa:bv/>
                <jpa:column name="Name" unique="false" nullable="false" insertable="true" updatable="true" table="LineOfBusiness" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="definiition" id="_1490799421423103">
                <jpa:bv/>
                <jpa:column name="Definiition" unique="false" nullable="false" insertable="true" updatable="true" table="LineOfBusiness" length="500"/>
            </jpa:basic>
            <jpa:many-to-one optional="false" connected-entity-id="_149079942142363" connected-attribute-id="_149079942142382" v="true" name="orgID" id="_1490799421423105">
                <jpa:bv/>
                <jpa:join-column name="ORGID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142368" connected-attribute-id="_1490799421424112" v="true" name="userRoleCollection" id="_1490799421423106">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:many-to-many connected-entity-id="_149079942142364" connected-attribute-id="_149079942142395" v="true" name="userProfileCollection" id="_1490799421423104">
                <jpa:bv/>
                <jpa:join-table name="LOB_USER">
                    <jpa:join-column name="LOB_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                    <jpa:inverse-join-column name="USER_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                </jpa:join-table>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_1490799421423101">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="LineOfBusiness"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="LineOfBusiness"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="OrganizationType" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142367">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" v="true" name="name" id="_1490799421423108">
                <jpa:bv/>
                <jpa:column name="Name" unique="false" nullable="false" insertable="true" updatable="true" table="OrganizationType" length="50"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="definition" id="_1490799421423109">
                <jpa:bv/>
                <jpa:column name="Definition" unique="false" nullable="false" insertable="true" updatable="true" table="OrganizationType" length="500"/>
            </jpa:basic>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142363" connected-attribute-id="_149079942142381" v="true" name="organizationCollection" id="_1490799421423110">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_1490799421423107">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="OrganizationType"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="OrganizationType"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="UserRole" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142368">
        <jpa:attributes>
            <jpa:many-to-one connected-entity-id="_149079942142366" connected-attribute-id="_1490799421423106" v="true" name="lobId" id="_1490799421424112">
                <jpa:bv/>
                <jpa:join-column name="LOB_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one connected-entity-id="_149079942142362" connected-attribute-id="_149079942142375" v="true" name="roleId" id="_1490799421424113">
                <jpa:bv/>
                <jpa:join-column name="ROLE_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one connected-entity-id="_149079942142364" connected-attribute-id="_149079942142396" v="true" name="userId" id="_1490799421424114">
                <jpa:bv/>
                <jpa:join-column name="USER_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:id attribute-type="Long" v="true" name="id" id="_1490799421424111">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="USER_ROLE"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="USER_ROLE"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Application" v="true" minimized="false" rootElement="_149079942142361" id="_149079942142369">
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" name="name" id="_1490799421424116">
                <jpa:bv/>
                <jpa:column name="Name" unique="false" nullable="true" insertable="true" updatable="true" table="Application" length="50"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="description" id="_1490799421424117">
                <jpa:bv/>
                <jpa:column name="Description" unique="false" nullable="true" insertable="true" updatable="true" table="Application" length="500"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="type" id="_1490799421424118">
                <jpa:bv/>
                <jpa:column name="type" unique="false" nullable="true" insertable="true" updatable="true" table="Application" length="50"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="meta" id="_1490799421424119">
                <jpa:bv/>
                <jpa:column name="META" unique="false" nullable="true" insertable="true" updatable="true" table="Application" length="2147483647"/>
            </jpa:basic>
            <jpa:one-to-many own="false" connected-entity-id="_149079942142362" connected-attribute-id="_149079942142374" v="true" name="roleCollection" id="_1490799421424120">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_1490799421424115">
                <jpa:bv/>
                <jpa:column name="ID" unique="false" nullable="false" insertable="true" updatable="true" table="Application"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Application"/>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:inf e="true" n="java.io.Serializable"/>
    <jpa:diagram>
        <plane elementRef="_149079942142361"/>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by javydreamercsw** [comment]
More details are appreciated, but give version 4 a try. It solved errors I had creating the model. Might be related.

**Comment by jGauravGupta** [comment]
Hi @debradsh ,

Can you share more details/steps to reproduce it.
