### ISSUE TITLE
Visualize DB Exception

### ISSUE THREAD

**Issue by dylanaut** [jeddict/jeddict#201]
Message : Exception Description: 

StackTrace : 
Local Exception Stack: 
Exception [EclipseLink-7246] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.netbeans.db.modeler.exception.DBValidationException
Exception Description: 
	at org.netbeans.jpa.modeler.db.accessor.DefaultClassSpecAccessor.process(DefaultClassSpecAccessor.java:59)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1816)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:573)
	at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:255)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:197)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:62)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:149)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:64)
	at org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:58)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$3(JPAModelerScene.java:382)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="de.aldisued.zutrittskontrolle" v="4.2" rws="_14926012067872" Pws="_14926012067872" cws="_14926012067872" persistenceUnitName="ZUTRITTSKONTROLLE_PU" sm="false" xs="false" id="_14926012067871" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity xre="false" compositePrimaryKeyType="D" compositePrimaryKeyClass="MitarbeiterPK" abs="false" class="Mitarbeiter" v="true" m="false" rootElement="_14926012067871" id="_1492609601518">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="java.sql.Date" v="true" name="eintrittsDatum" id="_14926100142006">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.util.Date" v="true" name="austrittsDatum" id="_14926101408637">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" v="true" name="name" id="_14926102258838">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="pin" id="_14926102883399">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:basic attribute-type="Personalnummer" v="true" name="personalnummer" id="_149261031610610">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:many-to-one optional="false" primaryKey="true" connected-entity-id="_1492611661759" connected-attribute-id="_149261217194547" v="true" name="mitarbeiterkreis" id="_149261217194546">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-one>
            <jpa:one-to-one own="true" orp="false" optional="true" primaryKey="true" connected-entity-id="_149261225005248" connected-attribute-id="_149261233179855" v="true" name="transponder" id="_149261233179854">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-one>
            <jpa:transient attribute-type="boolean" v="true" name="istRVL" id="_149261149169233">
                <jpa:des>derived</jpa:des>
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:transient>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14926096015653">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" v="true" name="version" id="_14926100057955">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="Mitarbeiter.findAll">
            <jpa:query>Select e from Mitarbeiter e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiter.findByEintrittsDatum">
            <jpa:query>Select m from Mitarbeiter m where m.eintrittsDatum=:eintrittsDatum</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiter.findByAustrittsDatum">
            <jpa:query>Select m from Mitarbeiter m where m.austrittsDatum=:austrittsDatum</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiter.findByName">
            <jpa:query>Select m from Mitarbeiter m where m.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiter.findByPin">
            <jpa:query>Select m from Mitarbeiter m where m.pin=:pin</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiter.findByPersonalnummer">
            <jpa:query>Select m from Mitarbeiter m where m.personalnummer=:personalnummer</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="FilialmitarbeiterPK" abs="false" class="Filialmitarbeiter" superclassId="_1492609601518" v="true" m="false" rootElement="_14926012067871" id="_1492610404153">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1492610524903" connected-attribute-id="_149261144905332" v="true" name="stammfiliale" id="_149261144905331">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-one>
        </jpa:attributes>
        <jpa:nq e="false" name="Filialmitarbeiter.findAll">
            <jpa:query>Select e from Filialmitarbeiter e</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="RegionalverkaufsleiterPK" abs="false" class="Regionalverkaufsleiter" superclassId="_1492609601518" v="true" m="false" rootElement="_14926012067871" id="_1492610460497">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1492610535997" connected-attribute-id="_149261288442158" v="true" name="verantworteteBereiche" id="_149261288442159">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-many>
            <jpa:many-to-many own="true" collection-type="java.util.List" connected-entity-id="_1492610524903" connected-attribute-id="_149261158426835" v="true" name="berechtigtFuerFilialen" id="_149261158426834">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-many>
            <jpa:transient attribute-type="List&lt;Filiale&gt;" v="true" name="verantworteteFilialen" id="_149261316849062">
                <jpa:des>derived</jpa:des>
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:transient>
        </jpa:attributes>
        <jpa:nq e="false" name="Regionalverkaufsleiter.findAll">
            <jpa:query>Select e from Regionalverkaufsleiter e</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="FilialePK" abs="false" class="Filiale" v="true" m="false" rootElement="_14926012067871" id="_1492610524903">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="boolean" v="true" name="verwaltetBerechtigungen" id="_149261073662020">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="filialNummer" id="_149261176892639">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="false" connected-entity-id="_1492610535997" connected-attribute-id="_149261098211524" v="true" name="gehörtZuBereich" id="_149261098211523">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-one>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1492610404153" connected-attribute-id="_149261144905331" v="true" name="filialmitarbeiter" id="_149261144905332">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-many>
            <jpa:many-to-many collection-type="java.util.List" connected-entity-id="_1492610460497" connected-attribute-id="_149261158426834" v="true" name="berechtigteRVL" id="_149261158426835">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149261169830538">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" v="true" name="version" id="_149261187025942">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="Filiale.findAll">
            <jpa:query>Select e from Filiale e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Filiale.findByFilialNummer">
            <jpa:query>Select f from Filiale f where f.filialNummer=:filialNummer</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Filiale.findByVerwaltetBerechtigungen">
            <jpa:query>Select f from Filiale f where f.verwaltetBerechtigungen=:verwaltetBerechtigungen</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Filiale.findByFilialNummer">
            <jpa:query>Select f from Filiale f where f.filialNummer=:filialNummer</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="D" compositePrimaryKeyClass="FilialbereichPK" abs="false" class="Filialbereich" v="true" m="false" rootElement="_14926012067871" id="_1492610535997">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1492610460497" connected-attribute-id="_149261288442159" v="true" name="verantwortlicherRVL" id="_149261288442158">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:many-to-one>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1492610524903" connected-attribute-id="_149261098211523" v="true" name="hatFilialen" id="_149261098211524">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149261053599717">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" v="true" name="version" id="_149261187843043">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="Filialbereich.findAll">
            <jpa:query>Select e from Filialbereich e</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="MitarbeiterkreisPK" abs="false" class="Mitarbeiterkreis" v="true" m="false" rootElement="_14926012067871" id="_1492611661759">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="bezeichnung" id="_149261182215840">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:basic>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1492609601518" connected-attribute-id="_149261217194546" v="true" name="mitarbeiter" id="_149261217194547">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149261166175936">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" v="true" name="version" id="_149261184243141">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="Mitarbeiterkreis.findAll">
            <jpa:query>Select e from Mitarbeiterkreis e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Mitarbeiterkreis.findByBezeichnung">
            <jpa:query>Select m from Mitarbeiterkreis m where m.bezeichnung=:bezeichnung</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="TransponderPK" abs="false" class="Transponder" v="true" m="false" rootElement="_14926012067871" id="_149261225005248">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>KREYJ</jpa:ath>
        <jpa:attributes>
            <jpa:one-to-one orp="false" optional="true" primaryKey="false" connected-entity-id="_1492609601518" connected-attribute-id="_149261233179854" v="true" name="identifiziert" id="_149261233179855">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
            </jpa:one-to-one>
            <jpa:id attribute-type="Long" v="true" name="transponderNummer" id="_149261225005251">
                <jpa:bv/>
                <jpa:kbv/>
                <jpa:vbv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Transponder.findAll">
            <jpa:query>Select e from Transponder e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Transponder.findByTransponderNummer">
            <jpa:query>Select m from Transponder m where m.transponderNummer=:transponderNummer</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the Jeddict
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14926012067872">
            <i ref="_149261225005248" x="281" y="572">
                <el/>
            </i>
            <i ref="_1492611661759" x="751" y="572">
                <el/>
            </i>
            <i ref="_1492610535997" x="1039" y="209">
                <el/>
            </i>
            <i ref="_1492610460497" x="751" y="32">
                <el/>
            </i>
            <i ref="_1492609601518" x="529" y="209">
                <el/>
            </i>
            <i ref="_1492610524903" x="32" y="209">
                <el/>
            </i>
            <i ref="_1492610404153" x="281" y="32">
                <el/>
            </i>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by rajkumar-alphaconnection** [comment]
I am getting same issue. Any steps to fix?

**Comment by jGauravGupta** [comment]
@rajkumar-alphaconnection , Can you share the modeler file. To reproduce it again.

**Comment by rajkumar-alphaconnection** [comment]
Hi,
Please find attached file.
[CartModel.jpa.zip](https://github.com/jeddict/jeddict/files/1101420/CartModel.jpa.zip)

**Comment by jGauravGupta** [comment]
Hi @rajkumar-alphaconnection ,

I can not reproduce the issue, DB Modeler is working fine : 

![cartmodel jpa](https://user-images.githubusercontent.com/15934072/27705167-bd84154c-5d2a-11e7-9ed4-5469310e6ba9.png)

**Comment by rajkumar-alphaconnection** [comment]
Hi @jGauravGupta , Thank you for your support. I think I made a mistake in installing plugins. now it is working fine.
Great Tool.

**Comment by javydreamercsw** [comment]
Looks like this one can be closed @jGauravGupta .
