### ISSUE TITLE
NullPointerException when trying to generate modeler from DB with huge tables

### ISSUE THREAD

**Issue by samyomar** [jeddict/jeddict#202]
Message : org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator$EntityModalGenerator.generateRelationship(JavaPersistenceModelGenerator.java:576)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator$EntityModalGenerator.generateRelationship(JavaPersistenceModelGenerator.java:576)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator$ModalGenerator.run(JavaPersistenceModelGenerator.java:359)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator.runImpl(JavaPersistenceModelGenerator.java:260)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator$Generator.run(JavaPersistenceModelGenerator.java:199)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator.generateModal(JavaPersistenceModelGenerator.java:99)
	at org.netbeans.jpa.modeler.reveng.database.generator.JavaPersistenceModelGenerator.generateModel(JavaPersistenceModelGenerator.java:82)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor.createModel(DBImportWizardDescriptor.java:180)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor.access$100(DBImportWizardDescriptor.java:55)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor$1.run(DBImportWizardDescriptor.java:93)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml

**Comment by jGauravGupta** [comment]
Hi @samyomar ,

Please attach the modeler file.

**Comment by jGauravGupta** [comment]
Hi @samyomar ,

Can you please share the sql queries .
