### ISSUE TITLE
Error while Visualize DB/JSON View (Beta)

### ISSUE THREAD

**Issue by piratron** [jeddict/jeddict#223]
Hi,

I use NB 8.2 and the JPA Modeler Plugin 4.3. When I call the "Visualize DB" function, I get the following message. I get the similar Message when I try to use the  "JSON View (Beta)" function.

Can you help me?

Message : org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:58)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:58)
	at org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:42)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$3(JPAModelerScene.java:385)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="vdm.vdmng.keyreader.entities" v="4.2.4" rws="_14987396561872" Pws="_14987396561872" cws="_14987396561872" sm="false" xs="false" id="_14987396561861" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity compositePrimaryKeyClass="IncidentPK" abs="false" class="Incident" v="true" jbn="false" xre="false" m="false" rootElement="_14987396561861" id="_1498739668907">
        <jpa:ath>lstelzne</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="creationTime" id="_149874075192611"/>
            <jpa:basic attribute-type="String" v="true" name="referenceID" id="_149874079138912"/>
            <jpa:basic attribute-type="String" v="true" name="errorCode" id="_149874080570113"/>
            <jpa:basic attribute-type="String" v="true" name="language" id="_149874131904532"/>
            <jpa:one-to-one own="true" primaryKey="false" connected-entity-id="_1498739784871" v="true" name="keyReader" id="_149874159333464"/>
            <jpa:one-to-one own="true" primaryKey="false" connected-entity-id="_1498740420378" v="true" name="servicePartner" id="_149874160190266"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14987396689423">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Incident.findAll">
            <jpa:query>Select e from Incident e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Incident.findByCreationTime">
            <jpa:query>Select i from Incident i where i.creationTime=:creationTime</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Incident.findByReferenceID">
            <jpa:query>Select i from Incident i where i.referenceID=:referenceID</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Incident.findByErrorCode">
            <jpa:query>Select i from Incident i where i.errorCode=:errorCode</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Incident.findByLanguage">
            <jpa:query>Select i from Incident i where i.language=:language</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="KeyReaderPK" abs="false" class="KeyReader" v="true" jbn="false" xre="false" m="false" rootElement="_14987396561861" id="_1498739784871">
        <jpa:ath>lstelzne</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="serialNo" id="_149874106282114"/>
            <jpa:basic attribute-type="String" v="true" name="brand" id="_149874107764515"/>
            <jpa:basic attribute-type="String" v="true" name="status" id="_149874108723616"/>
            <jpa:basic attribute-type="String" v="true" name="action" id="_149874109370117"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14987397848725">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="KeyReader.findAll">
            <jpa:query>Select e from KeyReader e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="KeyReader.findBySerialNo">
            <jpa:query>Select k from KeyReader k where k.serialNo=:serialNo</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="KeyReader.findByBrand">
            <jpa:query>Select k from KeyReader k where k.brand=:brand</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="KeyReader.findByStatus">
            <jpa:query>Select k from KeyReader k where k.status=:status</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="KeyReader.findByAction">
            <jpa:query>Select k from KeyReader k where k.action=:action</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="ServicePartnerPK" abs="false" class="ServicePartner" v="true" jbn="false" xre="false" m="false" rootElement="_14987396561861" id="_1498740420378">
        <jpa:ath>lstelzne</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="orgUnitID" id="_149874111224518"/>
            <jpa:basic attribute-type="String" v="true" name="userID" id="_149874112314919"/>
            <jpa:basic attribute-type="String" v="true" name="attribute" id="_149874112902120"/>
            <jpa:basic attribute-type="String" v="true" name="importerID" id="_149874117160526"/>
            <jpa:one-to-one own="true" primaryKey="false" connected-entity-id="_1498741134338" v="true" name="partnerId" id="_149874158958463"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14987404203797">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="ServicePartner.findAll">
            <jpa:query>Select e from ServicePartner e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ServicePartner.findByOrgUnitID">
            <jpa:query>Select s from ServicePartner s where s.orgUnitID=:orgUnitID</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ServicePartner.findByUserID">
            <jpa:query>Select s from ServicePartner s where s.userID=:userID</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ServicePartner.findByAttribute">
            <jpa:query>Select s from ServicePartner s where s.attribute=:attribute</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ServicePartner.findByImporterID">
            <jpa:query>Select s from ServicePartner s where s.importerID=:importerID</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="VersionPK" abs="false" class="Version" v="true" jbn="false" xre="false" m="false" rootElement="_14987396561861" id="_1498740456648">
        <jpa:ath>lstelzne</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="software" id="_149874127015729"/>
            <jpa:basic attribute-type="String" v="true" name="api" id="_149874128888530"/>
            <jpa:basic attribute-type="String" v="true" name="firmware" id="_149874130592531"/>
            <jpa:one-to-one own="true" primaryKey="false" connected-entity-id="_1498739784871" v="true" name="keyReader" id="_149874159726365"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14987404566499">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Version.findAll">
            <jpa:query>Select e from Version e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Version.findBySoftware">
            <jpa:query>Select v from Version v where v.software=:software</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Version.findByApi">
            <jpa:query>Select v from Version v where v.api=:api</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Version.findByFirmware">
            <jpa:query>Select v from Version v where v.firmware=:firmware</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="PartnerIdPK" abs="false" class="PartnerId" v="true" jbn="false" xre="false" m="false" rootElement="_14987396561861" id="_1498741134338">
        <jpa:ath>lstelzne</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="barnd" id="_149874114676523"/>
            <jpa:basic attribute-type="String" v="true" name="country" id="_149874115438924"/>
            <jpa:basic attribute-type="String" v="true" name="dealerID" id="_149874116097325"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149874113434121">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="PartnerId.findAll">
            <jpa:query>Select e from PartnerId e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="PartnerId.findByBarnd">
            <jpa:query>Select p from PartnerId p where p.barnd=:barnd</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="PartnerId.findByCountry">
            <jpa:query>Select p from PartnerId p where p.country=:country</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="PartnerId.findByDealerID">
            <jpa:query>Select p from PartnerId p where p.dealerID=:dealerID</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the Jeddict
 */</jpa:snp>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14987396561872">
            <i ref="_1498739784871" x="346" y="33"/>
            <i ref="_1498740420378" x="370" y="300"/>
            <i ref="_1498739668907" x="53" y="18"/>
            <i ref="_1498741134338" x="660" y="54"/>
            <i ref="_1498740456648" x="53" y="327"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Please check, have you installed the same version of all plugins including DB Modeler and JSONB Modeler etc.

**Comment by piratron** [comment]
Aaahhh, that was it. It works! Thank you very much! ☺

Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Donnerstag, 29. Juni 2017 17:10
An: jeddict/jeddict
Cc: Stelzner, Lars; Author
Betreff: Re: [jeddict/jeddict] Error while Visualize DB/JSON View (Beta) (#223)


Please check, have you installed the same version of all plugins including DB Modeler and JSONB Modeler etc.
