### ISSUE TITLE
error while generating the code

### ISSUE THREAD

**Issue by aloktech** [jeddict/jeddict#229]
Message : Test Source group creation failed

StackTrace : 
java.lang.IllegalStateException: Test Source group creation failed
	at org.netbeans.jcode.core.util.SourceGroupSupport.getTestSourceGroups(SourceGroupSupport.java:93)
	at org.netbeans.jcode.core.util.SourceGroupSupport.getTestSourceGroup(SourceGroupSupport.java:100)
	at org.netbeans.jcode.rest.controller.RESTGenerator.execute(RESTGenerator.java:215)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generateCRUD(ApplicationGenerator.java:205)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generate(ApplicationGenerator.java:75)
	at org.netbeans.jcode.generator.JEEApplicationGenerator.generate(JEEApplicationGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:131)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:93)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:447)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="com.imos.sample.model" v="4.2.4" rws="_14993939938922" Pws="_14993939938922" cws="_14993939938922" sm="false" xs="false" id="_14993939938911" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:mapped-superclass compositePrimaryKeyClass="BasicModelPK" abs="false" class="BasicModel" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394417570">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="java.util.Date" v="true" name="createdDate" id="_149939455058733">
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" v="true" name="deletedDate" id="_149939456358034">
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="updateDate" id="_149939652413787"/>
            <jpa:basic attribute-type="String" v="true" name="deleted" id="_149939594832770"/>
            <jpa:id attribute-type="Long" v="true" name="id" id="_149939442904130">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" v="true" name="version" id="_149939443279831"/>
        </jpa:attributes>
        <jpa:nq e="false" name="BasicModel.findAll">
            <jpa:query>Select m from BasicModel m</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="BasicModel.findByCreatedDate">
            <jpa:query>Select b from BasicModel b where b.createdDate=:createdDate</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="BasicModel.findByDeletedDate">
            <jpa:query>Select b from BasicModel b where b.deletedDate=:deletedDate</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="BasicModel.findByDeleted">
            <jpa:query>Select b from BasicModel b where b.deleted=:deleted</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="BasicModel.findByUpdateDate">
            <jpa:query>Select b from BasicModel b where b.updateDate=:updateDate</jpa:query>
        </jpa:nq>
    </jpa:mapped-superclass>
    <jpa:entity compositePrimaryKeyType="D" compositePrimaryKeyClass="UserPK" abs="false" class="Employee" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394000806">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="firstName" id="_14993940326175"/>
            <jpa:basic attribute-type="String" v="true" name="lastName" id="_14993940429506"/>
            <jpa:basic attribute-type="String" v="true" name="gender" id="_149939441017928"/>
            <jpa:basic attribute-type="String" v="true" name="joiningDate" id="_149939539587059"/>
            <jpa:basic attribute-type="String" v="true" name="reliefDate" id="_149939540432560"/>
            <jpa:basic attribute-type="String" v="true" name="mailId" id="_149939583315267"/>
            <jpa:basic attribute-type="String" v="true" name="mobileNumber" id="_149939584081968"/>
            <jpa:basic attribute-type="String" v="true" name="phoneNumber" id="_149939585471169"/>
            <jpa:basic attribute-type="String" v="true" name="employeeId" id="_149939629933277"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1499394575164" connected-attribute-id="_149939486471742" v="true" name="role" id="_149939486471541"/>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1499394056645" v="true" name="topics" id="_149939550349261"/>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1499396236039" connected-attribute-id="_149939696303395" v="true" name="employeeRatings" id="_149939696303496"/>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1499396397032" connected-attribute-id="_149939699464199" v="true" name="employeeVotings" id="_1499396994641100"/>
            <jpa:one-to-one own="true" orp="false" optional="true" primaryKey="true" connected-entity-id="_1499395088207" connected-attribute-id="_149939522819558" v="true" name="login" id="_149939522819457"/>
            <jpa:many-to-many collection-type="java.util.List" connected-entity-id="_1499394334499" connected-attribute-id="_149939482586739" v="true" name="projects" id="_149939482587040"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Employee.findAll">
            <jpa:query>Select e from Employee e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByFirstName">
            <jpa:query>Select u from Employee u where u.firstName=:firstName</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByLastName">
            <jpa:query>Select u from Employee u where u.lastName=:lastName</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByGender">
            <jpa:query>Select u from Employee u where u.gender=:gender</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByMailId">
            <jpa:query>Select u from Employee u where u.mailId=:mailId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByJoiningDate">
            <jpa:query>Select e from Employee e where e.joiningDate=:joiningDate</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByReliefDate">
            <jpa:query>Select e from Employee e where e.reliefDate=:reliefDate</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByMailId">
            <jpa:query>Select e from Employee e where e.mailId=:mailId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByMobileNumber">
            <jpa:query>Select e from Employee e where e.mobileNumber=:mobileNumber</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByPhoneNumber">
            <jpa:query>Select e from Employee e where e.phoneNumber=:phoneNumber</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByEmployeeId">
            <jpa:query>Select e from Employee e where e.employeeId=:employeeId</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="TopicPK" abs="false" class="Topic" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394056645">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="voteYes" id="_149939413927911"/>
            <jpa:basic attribute-type="String" v="true" name="voteNo" id="_149939414955312"/>
            <jpa:basic attribute-type="String" v="true" name="title" id="_149939428486120"/>
            <jpa:basic attribute-type="String" v="true" name="description" id="_149939429177421"/>
            <jpa:basic attribute-type="String" v="true" name="scheduleDate" id="_149939437380827"/>
            <jpa:basic attribute-type="boolean" v="true" name="lock" id="_149939492770443"/>
            <jpa:basic attribute-type="String" v="true" name="rating" id="_149939686804193"/>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1499394157430" v="true" name="comments" id="_149939426713519"/>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1499396236039" connected-attribute-id="_1499397053144103" v="true" name="employeeRatings" id="_1499397053145104"/>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1499396397032" connected-attribute-id="_1499397059121105" v="true" name="employeeVotings" id="_1499397059122106"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Topic.findAll">
            <jpa:query>Select e from Topic e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByTopicRating">
            <jpa:query>Select t from Topic t where t.topicRating=:topicRating</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByTopicDislike">
            <jpa:query>Select t from Topic t where t.topicDislike=:topicDislike</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByVoteYes">
            <jpa:query>Select t from Topic t where t.voteYes=:voteYes</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByVoteNo">
            <jpa:query>Select t from Topic t where t.voteNo=:voteNo</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByTitle">
            <jpa:query>Select t from Topic t where t.title=:title</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByDescription">
            <jpa:query>Select t from Topic t where t.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByScheduleDate">
            <jpa:query>Select t from Topic t where t.scheduleDate=:scheduleDate</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByLock">
            <jpa:query>Select t from Topic t where t.lock=:lock</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Topic.findByRating">
            <jpa:query>Select t from Topic t where t.rating=:rating</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="CommentPK" abs="false" class="Comment" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394157430">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="comment" id="_149939417457115"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Comment.findAll">
            <jpa:query>Select e from Comment e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Comment.findByComment">
            <jpa:query>Select c from Comment c where c.comment=:comment</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="ProjectPK" abs="false" class="Project" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394334499">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="name" id="_149939434394825"/>
            <jpa:basic attribute-type="String" v="true" name="description" id="_149939434989226"/>
            <jpa:many-to-many own="true" collection-type="java.util.List" connected-entity-id="_1499394000806" connected-attribute-id="_149939482587040" v="true" name="employees" id="_149939482586739"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Project.findAll">
            <jpa:query>Select e from Project e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Project.findByName">
            <jpa:query>Select p from Project p where p.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Project.findByDescription">
            <jpa:query>Select p from Project p where p.description=:description</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="RolePK" abs="false" class="Role" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499394575164">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="name" id="_149939459622737"/>
            <jpa:one-to-many orp="false" collection-type="java.util.List" connected-entity-id="_1499394000806" connected-attribute-id="_149939486471541" v="true" name="employees" id="_149939486471742"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Role.findAll">
            <jpa:query>Select e from Role e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Role.findByName">
            <jpa:query>Select r from Role r where r.name=:name</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="LoginPK" abs="false" class="Login" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499395088207">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="userid" id="_149939511362354"/>
            <jpa:basic attribute-type="String" v="true" name="password" id="_149939512037455"/>
            <jpa:basic attribute-type="String" v="true" name="salt" id="_149939512660156"/>
            <jpa:one-to-one orp="false" optional="true" primaryKey="false" connected-entity-id="_1499394000806" connected-attribute-id="_149939522819457" v="true" name="employee" id="_149939522819558"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Login.findAll">
            <jpa:query>Select e from Login e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Login.findByUserid">
            <jpa:query>Select l from Login l where l.userid=:userid</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Login.findByPassword">
            <jpa:query>Select l from Login l where l.password=:password</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Login.findBySalt">
            <jpa:query>Select l from Login l where l.salt=:salt</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="RatingPK" abs="false" class="Rating" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499396184896">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="value" id="_149939620935273"/>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1499396236039" v="true" name="employeeRatings" id="_1499397180575107"/>
        </jpa:attributes>
        <jpa:nq e="false" name="Rating.findAll">
            <jpa:query>Select e from Rating e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Rating.findByValue">
            <jpa:query>Select r from Rating r where r.value=:value</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyType="D" compositePrimaryKeyClass="EmployeeRatingPK" abs="false" class="EmployeeRating" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499396236039">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="ratingStatus" id="_149939648829785"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1499394000806" connected-attribute-id="_149939696303496" v="true" name="employee" id="_149939696303395"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1499394056645" connected-attribute-id="_1499397053145104" v="true" name="topic" id="_1499397053144103"/>
        </jpa:attributes>
        <jpa:nq e="false" name="EmployeeRating.findAll">
            <jpa:query>Select e from EmployeeRating e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeRating.findByEmployeeId">
            <jpa:query>Select e from EmployeeRating e where e.employeeId=:employeeId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeRating.findByTopicId">
            <jpa:query>Select e from EmployeeRating e where e.topicId=:topicId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeRating.findByRatingValue">
            <jpa:query>Select e from EmployeeRating e where e.ratingValue=:ratingValue</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeRating.findByRatingStatus">
            <jpa:query>Select e from EmployeeRating e where e.ratingStatus=:ratingStatus</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyType="D" compositePrimaryKeyClass="EmployeeVotingPK" abs="false" class="EmployeeVoting" superclassId="_1499394417570" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499396397032">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="votingType" id="_149939644923284"/>
            <jpa:basic attribute-type="String" v="true" name="votingStatus" id="_149939649952986"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1499394000806" connected-attribute-id="_1499396994641100" v="true" name="employee" id="_149939699464199"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1499394056645" connected-attribute-id="_1499397059122106" v="true" name="topic" id="_1499397059121105"/>
        </jpa:attributes>
        <jpa:nq e="false" name="EmployeeVoting.findAll">
            <jpa:query>Select e from EmployeeVoting e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeVoting.findByEmployeeId">
            <jpa:query>Select e from EmployeeVoting e where e.employeeId=:employeeId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeVoting.findByTopicId">
            <jpa:query>Select e from EmployeeVoting e where e.topicId=:topicId</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeVoting.findByVotingType">
            <jpa:query>Select e from EmployeeVoting e where e.votingType=:votingType</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="EmployeeVoting.findByVotingStatus">
            <jpa:query>Select e from EmployeeVoting e where e.votingStatus=:votingStatus</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:embeddable abs="false" class="Gender" v="true" jbn="false" xre="false" m="false" rootElement="_14993939938911" id="_1499395717506">
        <jpa:ath>Pintu</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="type" id="_149939573090765"/>
            <jpa:one-to-one own="true" orp="false" optional="true" primaryKey="false" connected-entity-id="_1499394000806" v="true" name="employee" id="_149939576465266"/>
        </jpa:attributes>
    </jpa:embeddable>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the Jeddict
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14993939938922">
            <i ref="_1499394157430" x="876" y="388"/>
            <i ref="_1499394056645" x="241" y="235"/>
            <i ref="_1499396184896" x="274" y="759"/>
            <i ref="_1499394417570" x="414" y="14"/>
            <i ref="_1499394000806" x="33" y="235"/>
            <i ref="_1499396397032" x="730" y="625"/>
            <i ref="_1499394334499" x="685" y="235"/>
            <i ref="_1499394575164" x="876" y="235"/>
            <i ref="_1499395088207" x="1027" y="235"/>
            <i ref="_1499395717506" x="133" y="625"/>
            <i ref="_1499396236039" x="446" y="625"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Which type or project , have you created for source code generation ?
Is it Maven > Web Application ?

**Comment by aloktech** [comment]
Hi Gaurav,

While generating source code from jpa model for webapp through maven.

Thanks & Regards,

Alok Ranjan Meher
