### ISSUE TITLE
Got NullPointerException while generating code

### ISSUE THREAD

**Issue by claytobo** [jeddict/jeddict#231]
Message : org.netbeans.jcode.core.util.POMManager.<init>(POMManager.java:85)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jcode.core.util.POMManager.<init>(POMManager.java:85)
	at org.netbeans.jcode.i18n.I18NGenerator.execute(I18NGenerator.java:64)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.execute(ApplicationGenerator.java:189)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.execute(ApplicationGenerator.java:191)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generateCRUD(ApplicationGenerator.java:206)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generate(ApplicationGenerator.java:73)
	at org.netbeans.jcode.generator.JEEApplicationGenerator.generate(JEEApplicationGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:130)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:92)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:450)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:89)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="com.bme.cart" v="4.4" rws="_15003324572072" Pws="_15003324572072" cws="_15003324572072" sm="false" xs="false" id="_15003324572061" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity compositePrimaryKeyClass="CustomerPK" abs="false" class="Customer" v="true" jbn="false" xre="false" m="false" rootElement="_15003324572061" id="_1500332524843">
        <jpa:ath>claytonbodine</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" xvt="" name="firstName" id="_15003326442305">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:column name="FNAME" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" xvt="" name="lastName" id="_15003327088166">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:column name="LNAME" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1500332871536" v="true" xvt="" name="orders" id="_150033303706114">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:join-column name="CUSTOMER_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" xvt="" name="id" id="_15003325248943">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Customer.findAll">
            <jpa:query>Select e from Customer e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Customer.findByFirstName">
            <jpa:query>Select c from Customer c where c.firstName=:firstName</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Customer.findByLastName">
            <jpa:query>Select c from Customer c where c.lastName=:lastName</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="ProductOrderPK" abs="false" class="ProductOrder" v="true" jbn="false" xre="false" m="false" rootElement="_15003324572061" id="_1500332871536">
        <jpa:ath>claytonbodine</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="int" v="true" xvt="" name="amount" id="_15003329037469">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1500332951620" v="true" xvt="" name="products" id="_150033327619217">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" xvt="" name="id" id="_15003328715377">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="ProductOrder.findAll">
            <jpa:query>Select e from ProductOrder e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ProductOrder.findByAmount">
            <jpa:query>Select p from ProductOrder p where p.amount=:amount</jpa:query>
        </jpa:nq>
        <jpa:table name="PRODUCT_ORDER"/>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="ProductPK" abs="false" class="Product" v="true" jbn="false" xre="false" m="false" rootElement="_15003324572061" id="_1500332951620">
        <jpa:ath>claytonbodine</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" xvt="" name="description" id="_150033296420512">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
            </jpa:basic>
            <jpa:basic attribute-type="float" v="true" xvt="" name="retailPrice" id="_150033297263313">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" v="true" xvt="" name="id" id="_150033295162010">
                <jpa:xwm nil="false" req="false"/>
                <jpa:xm nil="false" req="false"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select p from Product p where p.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByRetailPrice">
            <jpa:query>Select p from Product p where p.retailPrice=:retailPrice</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the Jeddict
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
        <cit>java.util.ArrayList</cit>
        <cit>java.util.LinkedList</cit>
        <cit>java.util.HashSet</cit>
        <cit>java.util.TreeSet</cit>
        <cit>java.util.HashMap</cit>
        <db u="jdbc:mysql://localhost:3306/cart?zeroDateTimeBehavior=convertToNull" n="root" p="r@msg@t3" d="com.mysql.jdbc.Driver"/>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_15003324572072">
            <i ref="_1500332951620" x="379" y="398"/>
            <i ref="_1500332871536" x="52" y="408"/>
            <i ref="_1500332524843" x="208" y="114"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Are you using Maven > Web Application project ?
If yes, Can you please share the complete project ?

**Comment by jGauravGupta** [comment]
Hi @claytobo ,
Please create Maven > Web Application for full stack application generation .
