### ISSUE TITLE
JPA diagram from Classes

### ISSUE THREAD

**Issue by vlapra** [jeddict/jeddict#232]
Some entities are not generated and errors are displayed.

v4.4.1 (latest version for NetBeans v8.2 Patch 2) from update center v8.2.p2 

Message : No enum constant org.netbeans.jpa.modeler.spec.OrderType.point_code

StackTrace : 
java.lang.IllegalArgumentException: No enum constant org.netbeans.jpa.modeler.spec.OrderType.point_code
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.netbeans.jpa.modeler.spec.OrderType.valueOf(OrderType.java:25)
	at org.netbeans.jpa.modeler.spec.Index.load(Index.java:92)
	at org.netbeans.jpa.modeler.spec.Table.load(Table.java:96)
	at org.netbeans.jpa.modeler.spec.Entity.load(Entity.java:195)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.lambda$load$0(IdentifiableClass.java:177)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass$$Lambda$174/318791404.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.load(IdentifiableClass.java:175)
	at org.netbeans.jpa.modeler.spec.Entity.load(Entity.java:192)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.lambda$load$0(IdentifiableClass.java:177)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass$$Lambda$174/318791404.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.load(IdentifiableClass.java:175)
	at org.netbeans.jpa.modeler.spec.Entity.load(Entity.java:192)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:51)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:41)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:83)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:609)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:380)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:363)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:204)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:201)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:201)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:334)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:415)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:407)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator.generateJPAModel(JPAModelGenerator.java:41)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor.generateJPAModel(RevEngWizardDescriptor.java:200)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor.lambda$instantiateJCREProcess$0(RevEngWizardDescriptor.java:128)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor$$Lambda$169/12933406.run(Unknown Source)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
```

**Comment by jShiwaniGupta** [comment]
Can you please share the modeler file and the enum class.

**Comment by vlapra** [comment]
[test1.txt](https://github.com/jeddict/jeddict/files/1161386/test1.txt)

Modeler file is attached. 

I do not know which enum class :(

**Comment by jShiwaniGupta** [comment]
Looks like you are doing reverse engineering task, so can you share the java classes.

**Comment by vlapra** [comment]
[classes.zip](https://github.com/jeddict/jeddict/files/1161400/classes.zip)

I hope I have attached all of them. Thanks!

**Comment by vlapra** [comment]
You are absolutely right. When I commented out the index definition at the AbstractPoint class diagram was generated correctly.

But the definition of the Index is correct (works with JPA - provider hibernate). 

It is strange :-(

**Comment by jShiwaniGupta** [comment]
Sorry we don't support the Hibernate specific annotation, yet it should not fail the reverse engineering process.
And of course , you can add custom annotation (Hibernate, Jackson etc) from modeler.

**Comment by vlapra** [comment]
BTW: It is probably JPA annotation not Hibernate (but it is not important when you will fix it)

javax.​persistence.​Table
public abstract Index[] indexes
(Optional) Indexes for the table. These are only used if table generation is in effect. Defaults to no additional indexes.
Returns:
The indexes
