### ISSUE TITLE
http://jpamodeler.github.io/updates.xml

### ISSUE THREAD

**Issue by TimTroy** [jeddict/jeddict#257]
##### **Overview of the issue**
Errors in NetBeans log

##### **Expected Outcome**

No errors

##### **Current Outcome**

WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: http://jpamodeler.github.io/updates.xml:21:1: Premature end of file.
INFO [org.netbeans.modules.autoupdate.services.UpdateUnitFactory]: Cannot read UpdateItem from UpdateProvider JPA Modeler[JPA Modeler] to http://jpamodeler.github.io/updates.xml
org.xml.sax.SAXParseException; systemId: http://jpamodeler.github.io/updates.xml; lineNumber: 21; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser.getUpdateItems(AutoupdateCatalogParser.java:197)
Caused: java.io.IOException: Failed to parse http://jpamodeler.github.io/updates.xml
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser.getUpdateItems(AutoupdateCatalogParser.java:199)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogProvider.getUpdateItems(AutoupdateCatalogProvider.java:143)
[catch] at org.netbeans.modules.autoupdate.services.UpdateUnitFactory.appendUpdateItems(UpdateUnitFactory.java:173)
	at org.netbeans.modules.autoupdate.services.UpdateUnitFactory.getUpdateUnits(UpdateUnitFactory.java:143)
	at org.netbeans.modules.autoupdate.services.UpdateManagerImpl$Cache.<init>(UpdateManagerImpl.java:271)
	at org.netbeans.modules.autoupdate.services.UpdateManagerImpl.getCache(UpdateManagerImpl.java:231)
	at org.netbeans.modules.autoupdate.services.UpdateManagerImpl.getUpdateUnits(UpdateManagerImpl.java:190)
	at org.netbeans.api.autoupdate.UpdateManager.getUpdateUnits(UpdateManager.java:92)
	at org.netbeans.jpa.modeler.update.version.UpdateHandler.findUpdates(UpdateHandler.java:130)
	at org.netbeans.jpa.modeler.update.version.UpdateHandler.checkAndHandleUpdates(UpdateHandler.java:63)
	at org.netbeans.jpa.modeler.update.version.JPAModelerInstaller.lambda$null$0(JPAModelerInstaller.java:66)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
INFO [jeddict]: Jeddict plugin is up to date.

##### **Steps to Reproduce**(Only for bug reports) 

Unsure how others can reproduce.  I see this every time NetBeans starts.

Going to url in stacktrace using IE, the same error is presented.

##### **Jeddict Version(s)**

Was using 4.1.1.  Uninstalled that and did fresh install to 4.7 and still have the issue.

**Comment by TimTroy** [comment]
I found and removed the JPA Modeler from NetBeans Update Centers.  This eliminated the errors reported, but, with latest Jeddict version, just seeing Warnings:

INFO [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: Unpaired license 00000008 without any module.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml:134:88: The content of element type "module_group" must match "(module_group|module)*".
INFO [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: Unpaired license 00000008 without any module.
INFO [null]: Last record repeated again.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml:134:88: The content of element type "module_group" must match "(module_group|module)*".
WARNING [null]: Last record repeated again.
INFO [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: Unpaired license 00000008 without any module.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml:134:88: The content of element type "module_group" must match "(module_group|module)*".
INFO [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: Unpaired license 00000008 without any module.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml:134:88: The content of element type "module_group" must match "(module_group|module)*".
