### ISSUE TITLE
JPA Diagram from Reverse Engineering (Classes) failed

### ISSUE THREAD

**Issue by AlphaSco** [jeddict/jeddict#273]
I get this error when Im trying to make an JPA diagram from entity classes:

`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.github.jeddict.reveng.klass.RevEngWizardDescriptor.generateJPAModel(RevEngWizardDescriptor.java:270)
	at io.github.jeddict.reveng.klass.RevEngWizardDescriptor.lambda$instantiateJCREProcess$1(RevEngWizardDescriptor.java:216)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)`

**Comment by jGauravGupta** [comment]
Fixed by commit : feaa06213e0994da55c65c80c64a110decfac2c3
