### ISSUE TITLE
Error creating model from classes: 2 counts of IllegalAnnotationExceptions

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#281]
##### **Error creating model from classes**

Doing reverse engineering it failed with the error below.

##### **Expected Outcome**

Successful reverse engineering.

##### **Current Outcome**

Message : 2 counts of IllegalAnnotationExceptions

StackTrace : 
com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "many-to-one". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at io.github.jeddict.jpa.spec.ManyToOne
		at private java.util.List io.github.jeddict.jpa.spec.extend.PersistenceAttributes.manyToOne
		at io.github.jeddict.jpa.spec.extend.PersistenceAttributes
		at io.github.jeddict.jpa.spec.PrimaryKeyAttributes
		at protected io.github.jeddict.jpa.spec.PrimaryKeyAttributes io.github.jeddict.jpa.spec.IdentifiableClass.attributes
		at io.github.jeddict.jpa.spec.IdentifiableClass
		at private io.github.jeddict.jpa.spec.IdentifiableClass io.github.jeddict.jpa.spec.SqlResultSetMapping.entity
		at io.github.jeddict.jpa.spec.SqlResultSetMapping
		at protected java.util.Set io.github.jeddict.jpa.spec.EntityMappings.sqlResultSetMapping
		at io.github.jeddict.jpa.spec.EntityMappings
	this problem is related to the following location:
		at io.github.jeddict.jpa.spec.bean.ManyToOneAssociation
		at private java.util.List io.github.jeddict.jpa.spec.bean.BeanAttributes.manyToOne
		at io.github.jeddict.jpa.spec.bean.BeanAttributes
		at private io.github.jeddict.jpa.spec.bean.BeanAttributes io.github.jeddict.jpa.spec.bean.BeanClass.attributes
		at io.github.jeddict.jpa.spec.bean.BeanClass
		at protected java.util.List io.github.jeddict.jpa.spec.EntityMappings.beanClass
		at io.github.jeddict.jpa.spec.EntityMappings
Two classes have the same XML type name "many-to-many". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at io.github.jeddict.jpa.spec.ManyToMany
		at private java.util.List io.github.jeddict.jpa.spec.extend.PersistenceAttributes.manyToMany
		at io.github.jeddict.jpa.spec.extend.PersistenceAttributes
		at io.github.jeddict.jpa.spec.PrimaryKeyAttributes
		at protected io.github.jeddict.jpa.spec.PrimaryKeyAttributes io.github.jeddict.jpa.spec.IdentifiableClass.attributes
		at io.github.jeddict.jpa.spec.IdentifiableClass
		at private io.github.jeddict.jpa.spec.IdentifiableClass io.github.jeddict.jpa.spec.SqlResultSetMapping.entity
		at io.github.jeddict.jpa.spec.SqlResultSetMapping
		at protected java.util.Set io.github.jeddict.jpa.spec.EntityMappings.sqlResultSetMapping
		at io.github.jeddict.jpa.spec.EntityMappings
	this problem is related to the following location:
		at io.github.jeddict.jpa.spec.bean.ManyToManyAssociation
		at private java.util.List io.github.jeddict.jpa.spec.bean.BeanAttributes.manyToMany
		at io.github.jeddict.jpa.spec.bean.BeanAttributes
		at private io.github.jeddict.jpa.spec.bean.BeanAttributes io.github.jeddict.jpa.spec.bean.BeanClass.attributes
		at io.github.jeddict.jpa.spec.bean.BeanClass
		at protected java.util.List io.github.jeddict.jpa.spec.EntityMappings.beanClass
		at io.github.jeddict.jpa.spec.EntityMappings

	at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:106)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:466)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:298)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:141)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1163)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:442)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at io.github.jeddict.jpa.modeler.initializer.JPAModelerUtil.<clinit>(JPAModelerUtil.java:282)
	at io.github.jeddict.reveng.klass.RevEngWizardDescriptor.instantiate(RevEngWizardDescriptor.java:203)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1028)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:580)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:414)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
	at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

ModelerFile : 
```xml
```

##### **Steps to Reproduce**(Only for bug reports) 

Reverse engineer classes from the net.sourceforge.javydreamercsw.database.storage.db https://github.com/javydreamercsw/tournament-manager/tree/master/Database-Storage/src/main/java/net/sourceforge/javydreamercsw/database/storage/db

##### **Jeddict Version(s)**

5.0

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw,
I cannot reproduce the issue, possibly, If you are using NetBeans 8.2, where previous version of Jeddict plugins are not uninstalled. Can you uninstall all Jeddict plugins and reinstall it so it will remove all older version of Jeddict plugin (if any left).

Why previous version plugins creates conflicts : 
In the recent release Jeddict build system migrated from Ant to Maven so module code-base name are also updated.

Please confirm, If you reproduced it on NetBeans 9.0.
