### ISSUE TITLE
NoSuchMethodError: com.sun.source.tree.CompilationUnitTree.getPackage() error on code generation if nb-javac module not installed

### ISSUE THREAD

**Issue by mehdimirhoseini** [jeddict/jeddict#303]
Message : com.sun.source.tree.CompilationUnitTree.getPackage()Lcom/sun/source/tree/PackageTree;

StackTrace : 
java.lang.NoSuchMethodError: com.sun.source.tree.CompilationUnitTree.getPackage()Lcom/sun/source/tree/PackageTree;
	at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.parsePackage(DefaultSourceLevelQueryImpl.java:203)
	at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.lambda$isModular$1(DefaultSourceLevelQueryImpl.java:148)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.isModular(DefaultSourceLevelQueryImpl.java:147)
	at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.getSourceLevel(DefaultSourceLevelQueryImpl.java:90)
	at org.netbeans.api.java.queries.SourceLevelQuery.getSourceLevel(SourceLevelQuery.java:105)
	at org.netbeans.modules.editor.java.JavaKit.getSourceLevel(JavaKit.java:113)
	at org.netbeans.modules.editor.java.JavaKit.lambda$initDocument$1(JavaKit.java:150)
	at org.netbeans.lib.java.lexer.JavaLexer.<init>(JavaLexer.java:74)
	at org.netbeans.api.java.lexer.JavaTokenId$1.createLexer(JavaTokenId.java:252)
	at org.netbeans.spi.lexer.LanguageHierarchy$Accessor.createLexer(LanguageHierarchy.java:353)
	at org.netbeans.lib.lexer.LexerInputOperation.<init>(LexerInputOperation.java:114)
	at org.netbeans.lib.lexer.TextLexerInputOperation.<init>(TextLexerInputOperation.java:51)
	at org.netbeans.lib.lexer.TextLexerInputOperation.<init>(TextLexerInputOperation.java:46)
	at org.netbeans.lib.lexer.inc.IncTokenList.reinit(IncTokenList.java:93)
	at org.netbeans.lib.lexer.TokenHierarchyOperation.setActiveImpl(TokenHierarchyOperation.java:305)
	at org.netbeans.lib.lexer.TokenHierarchyOperation.isActiveImpl(TokenHierarchyOperation.java:352)
	at org.netbeans.lib.lexer.TokenHierarchyOperation.languagePaths(TokenHierarchyOperation.java:597)
	at org.netbeans.api.lexer.TokenHierarchy.languagePaths(TokenHierarchy.java:261)
	at org.netbeans.modules.editor.indent.TaskHandler.collectTasks(TaskHandler.java:129)
	at org.netbeans.modules.editor.indent.IndentImpl.reformatLock(IndentImpl.java:191)
	at org.netbeans.modules.editor.indent.api.Reformat.lock(Reformat.java:89)
	at io.github.jeddict.orm.generator.util.ORMConverterUtil.getFormattedText(ORMConverterUtil.java:274)
	at io.github.jeddict.orm.generator.util.ORMConverterUtil.writeSnippet(ORMConverterUtil.java:248)
	at io.github.jeddict.orm.generator.service.ClassGeneratorService.generateEntityClasses(ClassGeneratorService.java:168)
	at io.github.jeddict.orm.generator.service.ClassGeneratorService.generate(ClassGeneratorService.java:90)
	at io.github.jeddict.orm.generator.JPASourceCodeGenerator.lambda$generate$0(JPASourceCodeGenerator.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.jeddict.orm.generator.JPASourceCodeGenerator.generate(JPASourceCodeGenerator.java:41)
	at io.github.jeddict.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:127)
	at io.github.jeddict.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:87)
	at io.github.jeddict.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:444)
	at io.github.jeddict.jcode.task.AbstractNBTask.run(AbstractNBTask.java:84)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings ptype="MONOLITH" ppkg="com.anisagroup.parspotil" epkg="domain" v="5.2" rws="_1544094818337133" Pws="_1544094818337133" cws="_1544094818337133" persistenceUnitName="DEFAULT_PU" sm="false" xs="false" id="_1544094818337132" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity compositePrimaryKeyClass="PersistencePK" abs="false" class="Persistence" v="true" jbn="false" xre="false" m="false" rootElement="_1544094818337132" id="_1544096212215134">
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" xvt="" name="version" id="_1544096212217135">
                <jpa:xwm/>
                <jpa:xm/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" xvt="" name="schemaLocation" id="_1544096212217136">
                <jpa:xwm/>
                <jpa:xm/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1544096212217137" v="true" xvt="" name="persistenceUnit" id="_1544096212219140">
                <jpa:xwm/>
                <jpa:xm/>
            </jpa:one-to-many>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="PersistenceUnitPK" abs="false" class="PersistenceUnit" v="true" xre="false" m="false" rootElement="_1544094818337132" id="_1544096212217137">
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="name" id="_1544096212217138"/>
            <jpa:basic attribute-type="String" v="true" name="transactionType" id="_1544096212217139"/>
            <jpa:basic attribute-type="String" v="true" name="provider" id="_1544096212221141"/>
            <jpa:basic attribute-type="String" v="true" name="excludeUnlistedClasses" id="_1544096212223142"/>
            <jpa:one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1544096212223143" v="true" name="properties" id="_1544096212223144"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="PropertiesPK" abs="false" class="Properties" v="true" xre="false" m="false" rootElement="_1544094818337132" id="_1544096212223143">
        <jpa:attributes>
            <jpa:one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1544096212223145" v="true" name="property" id="_1544096212225148"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity compositePrimaryKeyClass="PropertyPK" abs="false" class="Property" v="true" xre="false" m="false" rootElement="_1544094818337132" id="_1544096212223145">
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="name" id="_1544096212223146"/>
            <jpa:basic attribute-type="String" v="true" name="value" id="_1544096212225147"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:wsl>
        <jpa:ws n="Main" id="_1544094818337133">
            <i ref="_1544096212223145" x="496" y="154"/>
            <i ref="_1544096212223143" x="275" y="32"/>
            <i ref="_1544096212215134" x="275" y="373"/>
            <i ref="_1544096212217137" x="32" y="154"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
This issue is reproducible on JDK 8 when nb-javac module not installed.
@mehdimirhoseini reopen the ticket, If issue is reproducible after installing nb-javac plugin.
