### ISSUE TITLE
Error when create Microservice project

### ISSUE THREAD

**Issue by ArokLair** [jeddict/jeddict#324]

**Comment by ArokLair** [comment]
Message : Option 'js.nashorn-compat' is experimental and must be enabled with allowExperimentalOptions(). Do not use experimental options in production environments.

StackTrace : 
java.lang.IllegalArgumentException: Option 'js.nashorn-compat' is experimental and must be enabled with allowExperimentalOptions(). Do not use experimental options in production environments.
	at com.oracle.truffle.polyglot.OptionValuesImpl.failExperimental(OptionValuesImpl.java:195)
	at com.oracle.truffle.polyglot.OptionValuesImpl.findDescriptor(OptionValuesImpl.java:187)
	at com.oracle.truffle.polyglot.OptionValuesImpl.put(OptionValuesImpl.java:138)
	at com.oracle.truffle.polyglot.OptionValuesImpl.putAll(OptionValuesImpl.java:133)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:244)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:172)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:214)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.netbeans.libs.graalsdk.impl.GraalEnginesProvider.enumerateLanguages(GraalEnginesProvider.java:59)
	at org.netbeans.libs.graalsdk.impl.GraalEnginesProvider.factories(GraalEnginesProvider.java:49)
	at org.netbeans.api.scripting.Scripting$EngineManager.populateExtras(Scripting.java:148)
	at org.netbeans.api.scripting.Scripting$EngineManager.<init>(Scripting.java:133)
	at org.netbeans.api.scripting.Scripting.build(Scripting.java:120)
	at org.netbeans.api.scripting.Scripting.createManager(Scripting.java:65)
	at io.github.jeddict.jcode.util.FileUtil.getScriptEngine(FileUtil.java:309)
	at io.github.jeddict.jcode.util.FileUtil.expandTemplate(FileUtil.java:247)
	at io.github.jeddict.jcode.util.FileUtil.expandTemplate(FileUtil.java:232)
	at io.github.jeddict.jcode.util.FileUtil.expandTemplate(FileUtil.java:215)
	at io.github.jeddict.repository.RepositoryGenerator.generateAbstract(RepositoryGenerator.java:184)
	at io.github.jeddict.repository.RepositoryGenerator.execute(RepositoryGenerator.java:114)
	at io.github.jeddict.jcode.generator.ApplicationGenerator.execute(ApplicationGenerator.java:260)
	at io.github.jeddict.jcode.generator.ApplicationGenerator.generateCRUD(ApplicationGenerator.java:271)
	at io.github.jeddict.jcode.generator.ApplicationGenerator.generate(ApplicationGenerator.java:119)
	at io.github.jeddict.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:141)
	at io.github.jeddict.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:87)
	at io.github.jeddict.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:444)
	at io.github.jeddict.jcode.task.AbstractNBTask.run(AbstractNBTask.java:84)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)


ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings ptype="MICROSERVICE" ppkg="com.lafabril.ec.demoms.resources" epkg="domain" v="5.3" rws="_15657922746472" Pws="_15657922746472" cws="_15657922746472" persistenceUnitName="DEFAULT_PU" sm="false" xs="false" id="_15657922746471" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity compositePrimaryKeyClass="ProductoPK" abs="false" class="Producto" pclass="Entity_1" v="true" jbn="false" xre="false" m="false" rootElement="_15657922746471" id="_15657922768633">
        <jpa:ath>lulloa</jpa:ath>
        <jpa:removedAttributes/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" xvt="" name="descripcion" pname="attribute" id="_15657922836596">
                <jpa:xwm/>
                <jpa:xm/>
            </jpa:basic>
            <jpa:id attribute-type="Long" v="true" xvt="" name="id" id="_15657922768944">
                <jpa:xwm/>
                <jpa:xm/>
                <jpa:generated-value strategy="DEFAULT"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Producto.findAll">
            <jpa:query>Select e from Producto e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Producto.findByDescripcion">
            <jpa:query>Select p from Producto p where p.descripcion=:descripcion</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:wsl>
        <jpa:ws n="Main" id="_15657922746472">
            <i ref="_15657922768633" x="434" y="121"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Please share the environment(JDK version etc) and other details as mentioned in the ticket template.
