### ISSUE TITLE
Unable to create diagram (classloader conflict)

### ISSUE THREAD

**Issue by cailtin** [jeddict/jeddict#352]
remove radare and sqldal (both where in conflict) 

this looks like the java classloader hell

##### **Overview of the issue**

Message : Will not load class com.sun.xml.bind.v2.ContextFactory arbitrarily from one of ModuleCL@2f558e85[org.radar.radar.netbeans] and ModuleCL@4ccccff0[org.netbeans.libs.jaxb] starting from SystemClassLoader[742 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE

StackTrace : 
javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: Will not load class com.sun.xml.bind.v2.ContextFactory arbitrarily from one of ModuleCL@2f558e85[org.radar.radar.netbeans] and ModuleCL@4ccccff0[org.netbeans.libs.jaxb] starting from SystemClassLoader[742 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:442)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at io.github.jeddict.jpa.modeler.initializer.JPAModelerUtil.<clinit>(JPAModelerUtil.java:303)
	at io.github.jeddict.jpa.modeler.specification.model.workspace.WorkSpaceManager.<init>(WorkSpaceManager.java:70)
	at io.github.jeddict.jpa.modeler.initializer.JPAModelerScene.<init>(JPAModelerScene.java:103)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:140)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:78)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:66)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:61)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: Will not load class com.sun.xml.bind.v2.ContextFactory arbitrarily from one of ModuleCL@2f558e85[org.radar.radar.netbeans] and ModuleCL@4ccccff0[org.netbeans.libs.jaxb] starting from SystemClassLoader[742 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:179)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
	... 29 more

Caused : 
java.lang.ClassNotFoundException: Will not load class com.sun.xml.bind.v2.ContextFactory arbitrarily from one of ModuleCL@2f558e85[org.radar.radar.netbeans] and ModuleCL@4ccccff0[org.netbeans.libs.jaxb] starting from SystemClassLoader[742 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:179)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:442)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at io.github.jeddict.jpa.modeler.initializer.JPAModelerUtil.<clinit>(JPAModelerUtil.java:303)
	at io.github.jeddict.jpa.modeler.specification.model.workspace.WorkSpaceManager.<init>(WorkSpaceManager.java:70)
	at io.github.jeddict.jpa.modeler.initializer.JPAModelerScene.<init>(JPAModelerScene.java:103)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:140)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:78)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:66)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:61)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

ModelerFile : 
```xml
```

**Comment by jGauravGupta** [comment]
Hi @cailtin,
Please uninstall RADAR and SQLDAL plugin and report the issue in RADAR and SQLDAL plugin repository as JAXB dependencies are already distributed by Apache NetBeans IDE then these plugins must not package JAXB dependencies which creates classpath issue.

Closing this issue, please let me know if more details or help needed.
