### ISSUE TITLE
MultiException with plugin netbeans-rest-client calling google.de

### ISSUE THREAD

**Issue by Chris2011** [jeddict/jeddict#551]
##### **Overview of the issue**

Using netbeans-rest-client with jeddict throws exception while calling google.de or twitter.de. See here for a detailed discussion: https://github.com/javierllorente/netbeans-rest-client/issues/13

When I disable jeddict, everysthing works fine.

##### **Expected Outcome**

I should get a response from the mentioned URLs.

##### **Current Outcome**

```
MultiException stack 1 of 2
java.util.ServiceConfigurationError: jakarta.json.spi.JsonProvider: org.glassfish.json.JsonProviderImpl not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1268)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1270)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:124)
	at jakarta.json.Json.createReaderFactory(Json.java:218)
	at org.eclipse.parsson.media.JsonValueBodyReader.<init>(JsonValueBodyReader.java:45)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1356)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:395)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:308)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:152)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219)
	at org.glassfish.jersey.client.ClientMessageBodyFactory$MessageBodyWorkersConfigurator.postInit(ClientMessageBodyFactory.java:75)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:468)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:468)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at com.javierllorente.netbeans.rest.client.RestClient.request(RestClient.java:189)
	at com.javierllorente.netbeans.rest.client.ui.RestClientTopComponent.lambda$request$4(RestClientTopComponent.java:284)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: create on org.eclipse.parsson.media.JsonValueBodyReader
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:428)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:308)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:152)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219)
	at org.glassfish.jersey.client.ClientMessageBodyFactory$MessageBodyWorkersConfigurator.postInit(ClientMessageBodyFactory.java:75)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:468)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:468)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at com.javierllorente.netbeans.rest.client.RestClient.request(RestClient.java:189)
	at com.javierllorente.netbeans.rest.client.ui.RestClientTopComponent.lambda$request$4(RestClientTopComponent.java:284)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

##### **Steps to Reproduce**(Only for bug reports)

1. Install jeddict version 6.2.0 in Apache NetBeans
2. Install netbeans-rest-client 0.6.0 in NetBeans
3. Restart NetBeans
4. Go to tools and choose REST Client
5. type next to GET google.de
6. Hit enter or click send.
7. Exception is thrown

##### **Jeddict Version(s)**
Jeddict: 6.2.0

Product Version: Apache NetBeans IDE 20
Java: 11.0.19; Java HotSpot(TM) 64-Bit Server VM 11.0.19+9-LTS-224
Runtime: Java(TM) SE Runtime Environment 11.0.19+9-LTS-224
System: Windows 11 version 10.0 running on amd64; Cp1252; de_DE (nb)
User directory: C:\Users\clenz\AppData\Roaming\NetBeans\20
Cache directory: C:\Users\clenz\AppData\Local\NetBeans\Cache\20

**Comment by jGauravGupta** [comment]
The issue was in release packaging script, which is fixed now, checkout the latest version 6.5.0.
