### ISSUE TITLE
Error opening .jpa file when using NetBeans dark metal look and feel

### ISSUE THREAD

**Issue by pedrohidalgo** [jeddict/jeddict#73]
Message : org.netbeans.modeler.scene.vmd.AbstractPModelerScene.init(AbstractPModelerScene.java:150)

StackTrace : 
java.lang.NullPointerException
    at org.netbeans.modeler.scene.vmd.AbstractPModelerScene.init(AbstractPModelerScene.java:150)
    at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.init(JPAModelerScene.java:329)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:145)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:72)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:64)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:59)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 

``` xml

```

**Comment by jGauravGupta** [comment]
Hi @pedrohidalgo,

Issue is not re-producible with this http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans plugin. Can you please help and guide to re-produce the issue.
